language: cpp

compiler:
  - gcc
  - clang

os:
  - osx

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc

    - os: linux
      dist: bionic
      compiler: clang

script:
  - ./build.sh
  - ./test.sh
